name: Update environments

on:
  workflow_dispatch
  #push:
    #branches:
      #- main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set environment variables on remote server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        SECURITY_KEY: ${{ secrets.SECURITY_KEY }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        DG_API_KEY: ${{ secrets.DG_API_KEY }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
           echo '$SSH_PASSWORD' | sudo -S bash -c 'echo \"DB_CONNECTION_STRING=$DB_CONNECTION_STRING\" >> /etc/environment'
           echo '$SSH_PASSWORD' | sudo -S bash -c 'echo \"SECURITY_KEY=$SECURITY_KEY\" >> /etc/environment'
           echo '$SSH_PASSWORD' | sudo -S bash -c 'echo \"SMTP_PASSWORD=$SMTP_PASSWORD\" >> /etc/environment'
           echo '$SSH_PASSWORD' | sudo -S bash -c 'echo \"GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET\" >> /etc/environment'
           echo '$SSH_PASSWORD' | sudo -S bash -c 'echo \"DG_API_KEY=$DG_API_KEY\" >> /etc/environment'
        "
        


    
